### ISSUE TITLE
Icon Quality

### ISSUE THREAD

**Issue by adamwitiak** [TillDiebelt/EclipseLevelInCharacterSelection#2]
<img width="1194" alt="image" src="https://github.com/TillDiebelt/EclipseLevelInCharacterSelection/assets/98412641/42cbdc49-dc05-43c5-995d-42c4c4eca78a">

This is what my icons look like at the moment. Has this mod been updated since SotV?

**Comment by TillDiebelt** [comment]
I am sorry to hear it is not working, as it works for me fine on current patch:

![grafik](https://github.com/TillDiebelt/EclipseLevelInCharacterSelection/assets/29427620/3f2a5a94-ab26-485f-822f-a60d58879087)

Can you give any other information about other mods, graphic settings and platform/OS you play on, so I can take a closer look?
